Made SOL work under Opal2

diff --git a/sol/opal2-wrapper b/sol/opal2-wrapper
--- a/sol/opal2-wrapper
+++ b/sol/opal2-wrapper
@@ -1,22 +1,19 @@
 #!/bin/bash
-# 4/1/2016 - Tyson modified the local install directory to fit sol-comet from eemt
-# This script starts up a local Sol instance, and uses SSH to
-# submit workers on SDSC Comet.
+
+# this is just a wrapper around run-master which sets up the workdir expected by
+# opal2
 
 set -e
 
-# settings
-LOCAL_WORK_DIR=`pwd`
-LOCAL_SOL_INSTALL=/srv/git/sol-ot-comet-dev
+# WORK_DIR is also used by run-master
+export WORK_DIR=`pwd`
 
-export TCP_LOW_PORT=20000
-export TCP_HIGH_PORT=60000 
-
-# should be in the container
-export PYTHONPATH=/opt/eemt/lib/python2.6/site-packages:/opt/eemt/lib64/python2.6/site-packages
+# figure out the full path for the sol directory
+SOL_INSTALL=`dirname $0`
+SOL_INSTALL=`cd $LOCAL_SOL_INSTALL && pwd`
 
 # safety check
-if [ -e run-workflow ]; then
+if [ -e run-master -o -e run-workflow ]; then
     echo "Do not run from the Sol checkout!"
     exit 1
 fi
@@ -24,25 +21,16 @@ fi
 # arguments
 DEM=$1
 
-cp $LOCAL_SOL_INSTALL/* .
+# tell run-master where to do the work
 
-# we also need the password file
-cp ~/.eemt-makeflow-password .
+set +e
+$SOL_INSTALL/run-master $DEM
+EXIT_CODE=$?
+set -e
 
-# run the workflow
-singularity exec \
-  --home $PWD:/srv \
-  --pwd /srv \
-  --scratch /var/tmp \
-  --scratch /tmp \
-  --contain --ipc --pid \
-  /srv/containers/eemt-current.img \
-  /srv/run-workflow \
-    --name EEMT \
-    -O /srv/work \
-    /srv/$DEM
+# clean up
+rm -f eemt-current.img
+rm -f .eemt-makeflow-password
 
-echo
-echo "Output files in $LOCAL_WORK_DIR"
-echo
+exit $EXIT_CODE
 
diff --git a/sol/opal2-wrapper-urldem b/sol/opal2-wrapper-urldem
--- a/sol/opal2-wrapper-urldem
+++ b/sol/opal2-wrapper-urldem
@@ -17,25 +17,24 @@ function niceexit {
         fi
 }
 
-set -e
+# WORK_DIR is also used by run-master
+export WORK_DIR=`pwd`
 
-# setting a WORK_DIR singlas to run-master that it does not need to set up
-# a new one
-export WORK_DIR=`readlink -f .`
+# figure out the full path for the sol directory
+SOL_INSTALL=`dirname $0`
+SOL_INSTALL=`cd $SOL_INSTALL && pwd`
 
-# figure out what the base dir of this script is
-SOL_INSTALL_DIR=`dirname $0`
-SOL_INSTALL_DIR=`cd $SOL_INSTALL_DIR && pwd`
-
-# safty check
-if [ -e run-master ]; then
-    niceexit 1 "" "" "Error: Do not run from the Sol checkout!"
+# safety check
+if [ -e run-master -o -e run-workflow ]; then
+    echo "Do not run from the Sol checkout!"
+    exit 1
 fi
 
 echo "[`date`] setting up for the workflow..."
 t0=`date +%s`
 # arguments
 DEMURL=$1
+
 zipfile="output.zip"
 if [ ! -z "$2" ]; then
         oname="`basename $2`"
@@ -43,19 +42,16 @@ if [ ! -z "$2" ]; then
         zipfile="$oname"
 fi
 
-tdir=/tmp/eemt_tmp.$RANDOM
-mkdir -p $tdir
-cd $tdir
+t0=`date +%s`
+
 DEMTAR=`basename $DEMURL`
 wget -nv $DEMURL 2>&1
 [ $? -ne 0 ] && niceexit 1 $DEMURL $zipfile "Error: could not download DEM $DEMURL."
 echo "[`date`] downloaded DEM from $DEMURL"
 
-cd $WORK_DIR/
-tar xfz $tdir/$DEMTAR
+tar xfz $DEMTAR
 [ $? -ne 0 ] && niceexit 1 $DEMURL $zipfile "Error: could not unzip DEM from $DEMURL."
 DEM=$(basename `ls *.tif | head -n 1`) 
-rm -fr $tdir/$DEMTAR
 
 # let's make sure the dem has a sane name
 DEM_NAME_FIXED=`echo "$DEM" | sed 's/\.tif$//' | sed 's/\./_/g'`".tif"
@@ -65,21 +61,19 @@ if [ "$DEM" != "$DEM_NAME_FIXED" ]; then
     DEM=$DEM_NAME_FIXED
 fi
 
-cd $SOL_INSTALL_DIR
-
 t1=`date +%s`
-# run the workflow
-echo "[`date`] starting the workflow..."
-echo
-echo "================================================================="
-echo
-./run-master $WORK_DIR/$DEM 2>&1
+$SOL_INSTALL/run-master $DEM
 retcode=$?
 t2=`date +%s`
 if [ $retcode -eq 0 ]; then
         echo "[`date`] archiving output ..."
-        cd $WORK_DIR && zip -r $zipfile global/monthly insol/monthly
+        (cd work && zip -r ../$zipfile global/monthly insol/monthly)
 fi
+
+# clean up
+rm -f eemt-current.img
+rm -f .eemt-makeflow-password
+
 echo
 echo "[`date`] Finished, workflow returned exit code $retcode. Output files in $WORK_DIR . Output archive in $WORK_DIR/$zipfile ."
 echo "Time in sec: download `expr $t1 \- $t0` ; workflow `expr $t2 \- $t1`"
